sm/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_dashboard/<int:user_id>/', views.user_dashboard, name='user_dashboard'),
    path('Edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('phone_login/', views.phone_login, name='phone_login'),
]

sm/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.each_post, name='each_post'),
    path('Add_post/<int:user_id>/', views.add_post, name='add_post'),
    path('Delete_post/<int:user_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('Edit_post/<int:user_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('Add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

sm/sm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

sm/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{message.tags}}">{{message}}</p>
    {% endfor %}
{% endif %}

sm/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <a class="nav-link active" style="color:#47803e;" href="{% url 'posts:all_posts'%}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="nav-link active" style="color:#85c27c;" href="{% url 'accounts:user_logout'%}">Logout</a>
            <a class="nav-link active" style="color:#85c27c;" href="{% url 'accounts:user_dashboard' request.user.id %}">Profile</a>
        {% else %}
            <a class="nav-link active" style="color:#85c27c;" href="{% url 'accounts:user_login'%}">Login</a>
            <a class="nav-link active" style="color:#85c27c;" href="{% url 'accounts:user_register'%}">Register</a>
            <a class="nav-link active" style="color:#85c27c;" href="{% url 'accounts:phone_login' %}">Phone Login</a>
        {% endif %}
    </div>
  </div>
</nav>