sm/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_dashboard/<int:user_id>/', views.user_dashboard, name='user_dashboard'),
    path('Edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('phone_login/', views.phone_login, name='phone_login'),
]

sm/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.each_post, name='each_post'),
    path('Add_post/<int:user_id>/', views.add_post, name='add_post'),
    path('Delete_post/<int:user_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('Edit_post/<int:user_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('Add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

sm/sm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

sm/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)
    phone = models.PositiveIntegerField(null=True, blank=True)


def profile_save(sender, **kwargs):
    if kwargs['created']:
        p = Profile(user=kwargs['instance'])
        p.save()


post_save.connect(receiver=profile_save, sender=User)

sm/accounts/forms.py
from django import forms
from .models import Profile

login_messages = {
    'invalid': 'معتبر نیست',
    'required': 'این فیلد اجباری است'
}

register_messages = {
    'invalid': 'لطفا یک ایمیل معتبر وارد کنید',
    'required': 'این فیلد اجباری است'
}


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=50, error_messages=login_messages, widget=forms.TextInput(attrs={'class': 'form-control mt-3 mb-4 ', 'placeholder': 'Username'}))
    password = forms.CharField(max_length=50, error_messages=login_messages, widget=forms.PasswordInput(attrs={'class': 'form-control  mt-4 mb-3 ', 'placeholder': 'Password'}))


class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=50, error_messages=register_messages, widget=forms.TextInput(attrs={'class': 'form-control mt-3 mb-4', 'placeholder': 'Username'}))
    email = forms.EmailField(max_length=70, error_messages=register_messages, widget=forms.EmailInput(attrs={'class': 'form-control mt-4 mb-3', 'placeholder': 'Email'}))
    password = forms.CharField(max_length=50, error_messages=register_messages, widget=forms.PasswordInput(attrs={'class': 'form-control mt-4 mb-3', 'placeholder': 'Password'}))


class EditProfile(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control  mt-4 mb-4', 'placeholder': 'Email'}))

    class Meta:
        model = Profile
        fields = ('bio', 'age', 'phone')
        widgets = {
            'bio': forms.TextInput(attrs={'class': 'form-control mt-4 mb-4', 'placeholder': 'Bio'}),
            'age': forms.NumberInput(attrs={'class': 'form-control ', 'placeholder': 'Age'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control ', 'placeholder': 'phone number'}),
        }


class PhoneLoginForm(forms.Form):
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control ', 'placeholder': 'phone number'}))

    def clean_phone(self):
        phone = Profile.objects.filter(phone=self.cleaned_data['phone'])
        if not phone.exists():
            raise forms.ValidationError('this phone number does not exists')
        return self.cleaned_data['phone']

sm/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegisterForm, UserLoginForm, EditProfile, PhoneLoginForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from posts.models import Post
from django.contrib.auth.decorators import login_required
from random import randint
from kavenegar import *


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'You logged in successfully', 'success')
                return redirect('posts:all_posts')
            else:
                messages.error(request, 'Username or Password is wrong try again', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/user_login.html', {'form': form})


def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(username=cd['username'], email=cd['email'], password=cd['password'])
            login(request, user)
            messages.success(request, 'You registered successfully', 'success')
            return redirect('posts:all_posts')
        else:
            messages.error(request, 'Registration failed try again', 'danger')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/user_register.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('posts:all_posts')


@login_required
def user_dashboard(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    posts = Post.objects.filter(user=user_id)
    self_dash = False
    if request.user.id == user_id:
        self_dash = True
    return render(request, 'accounts/user_dashboard.html', {'user': user, 'posts': posts, 'self_dash': self_dash})


@login_required
def edit_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = EditProfile(request.POST, instance=user.profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.phone = form.cleaned_data['phone']
            new_form.save()
            user.email = form.cleaned_data['email']
            user.save()
            messages.success(request, 'Your profile edited successfully', 'success')
            return redirect('accounts:user_dashboard', user_id)
    else:
        form = EditProfile(instance=user.profile, initial={'email': request.user.email})
    return render(request, 'accounts/edit_profile.html', {'form': form})


def phone_login(request):
    if request.method == 'POST':
        form = PhoneLoginForm(request.POST)
        if form.is_valid():
            phone = f"0{form.cleaned_data['phone']}"
            rand_number = randint(1000, 9999)
            api = KavenegarAPI('374A676B4F374D397346574466655235723773336E4977'
                               '76574255647743694C476370676E36432F414F4D3D')
            params = {'receptor': phone, 'message': rand_number}
            api.sms_send(params)
            messages.success(request, 'sms sent to your phone', 'success')

    else:
        form = PhoneLoginForm()
    return render(request, 'accounts/phone_login.html', {'form': form})

sm/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}
{% block content %}
  <div class="card-body bg-dark rounded mt-4 text-white" style=" margin: auto;
  width: 90%;
  border: 5px;
  padding: 20px;">
    <form action="" method="post">
    <div class="card-body text-center">
      {% csrf_token %}
      {{form.none_field_errors}}
      {{form.bio.errors}}
      {{form.bio}}

      {{form.age.errors}}
      {{form.age}}

      {{form.email.errors}}
      {{form.email}}

      {{form.phone.errors}}
      {{form.phone}}

    </div><hr>
    <div class="text-center">
        <input class="btn" type="submit" value="Edit Profile" style="background-color:#85c27c;">
    </div>
</form>
  </div>
{% endblock %}

sm/accounts/templates/accounts/phone_login.html
{% extends 'base.html' %}
{% block title %}Phone Login{% endblock %}
{% block content %}
<form action="" method="post" novalidate>
    <div class="card-body bg-dark rounded mt-4 text-white" style=" margin: auto; width: 40%; border: 5px; padding: 20px;">
          <div class="text-center">
                {% csrf_token %}
                {{form.none_field_errors}}

                {{form.phone.errors}}
                {{form.phone}}
          </div>
        <div class="text-center">
            <input class="btn mt-4" type="submit" value="Send" style="background-color:#85c27c;">
        </div>
    </div>

</form>

{% endblock %}

sm/accounts/templates/accounts/user_dashboard.html
{% extends 'base.html' %}
{% block title %}{{user.username}}| Profile {% endblock %}
{% block content %}
<div class="text-center">
    <h3 style="color: #466b4f;">{{user.username}}</h3>
    <p>{{user.profile.bio}}</p>
</div>
{% if self_dash %}
    <a class="card-link" style="text-decoration: none; color: #47803e;" href="{% url 'posts:add_post' user.id %}">Add Post &nbsp;</a>
    <a class="card-link" style="text-decoration: none; color: #47803e;" href="{% url 'accounts:edit_profile' user.id %}">Edit Profile</a><hr>
{% endif %}
{% for post in posts %}
    <div class="card m-3">
        <p class="card-header"><a href="{% url 'accounts:user_dashboard' request.user.id %}" style="text-decoration: none; color: #466b4f;">{{post.user}}</a> | {{post.created}}</p>
        <a class="card-footer" href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black;"><p>{{post.body | truncatechars:500}}</p></a>
    </div>
{% empty %}
    <p class="text-center">there is no post yet</p>
{% endfor %}
{% endblock %}

sm/accounts/templates/accounts/user_login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<form action="" method="post" novalidate>

    <div class="card-body bg-dark rounded mt-4 text-white" style=" margin: auto;
  width: 40%;
  border: 5px;
  padding: 20px;">
          <div class="text-center">
    {% csrf_token %}
    {{form.none_field_errors}}

    {{form.username.errors}}
    {{form.username}}

    {{form.password.errors}}
    {{form.password}}
          </div>
        <div class="text-center">
            <input class="btn" type="submit" value="Login" style="background-color:#85c27c;">
        </div>
    </div>

</form>


{% endblock %}

sm/accounts/templates/accounts/user_register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <form action="" method="post" novalidate>
        <div class="card-body bg-dark rounded mt-4 text-white" style=" margin: auto;
      width: 40%;
      border: 5px;
      padding: 20px;">
            <div class="text-center">
                {% csrf_token %}
                {{form.none_field_errors}}

                {{form.username.errors}}
                {{form.username}}

                {{form.email.errors}}
                {{form.email}}

                {{form.password.errors}}
                {{form.password}}
            </div>
        <div class="text-center">
        <input class="btn" type="submit" value="Register" style="background-color:#85c27c;">
        </div>
            </div>
    </form>
{% endblock %}