sm/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_dashboard/<int:user_id>/', views.user_dashboard, name='user_dashboard'),
    path('Edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('phone_login/', views.phone_login, name='phone_login'),
]

sm/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.each_post, name='each_post'),
    path('Add_post/<int:user_id>/', views.add_post, name='add_post'),
    path('Delete_post/<int:user_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('Edit_post/<int:user_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('Add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

sm/sm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

sm/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.CharField(max_length=30)
    body = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

    def get_absolute_url(self):
        return reverse('posts:each_post', args=[self.created.year, self.created.month, self.created.day, self.slug])

    def like_count(self):
        return self.post_vote.count()

    def can_like(self, user):
        user_vote = user.user_vote.all()
        query = user_vote.filter(post=self)
        if query.exists():
            return True
        return False

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment_post')
    body = models.TextField(max_length=500)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='comment_reply', null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-{self.body[:30]}'

    class Meta:
        ordering = ('-created',)


class Vote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_vote')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote')

    def __str__(self):
        return f'{self.user}-{self.post}'

sm/posts/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': '...'}),
        }


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': '...'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '...'}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '...'}),
        }

sm/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Vote
from .forms import AddPostForm, EditPostForm, CommentForm, ReplyForm
from django.utils.text import slugify
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def all_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts/all_posts.html', {'posts': posts})


def each_post(request, year, month, day, slug):
    post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, slug=slug)
    reply_form = ReplyForm()
    can_like = False
    if request.user.is_authenticated:
        if Post.can_like(self=post, user=request.user):
            can_like = True
    comments = Comment.objects.filter(post=post, is_reply=False)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'Your comment added successfully', 'success')
    else:
        form = CommentForm()
    return render(request, 'posts/each_post.html',
                  {'post': post, 'comments': comments, 'form': form, 'reply_form': reply_form, 'can_like': can_like})


@login_required
def add_post(request, user_id):
    if request.user.id == user_id:
        if request.method == "POST":
            form = AddPostForm(request.POST)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.user = request.user
                new_post.slug = slugify(form.cleaned_data['body'][:30])
                new_post.save()
                messages.success(request, 'Your post added successfully', 'success')
                return redirect('accounts:user_dashboard', user_id)
        else:
            form = AddPostForm()
        return render(request, 'posts/add_post.html', {'form': form})
    else:
        return redirect("posts:all_posts")


@login_required
def delete_post(request, user_id, post_id):
    if request.user.id == user_id:
        post = get_object_or_404(Post, pk=post_id)
        post.delete()
        messages.success(request, 'Your post deleted successfully', 'success')
    return redirect('accounts:user_dashboard', user_id)


@login_required
def edit_post(request, user_id, post_id):
    if request.user.id == user_id:
        post = get_object_or_404(Post, pk=post_id)
        if request.method == "POST":
            form = EditPostForm(request.POST, instance=post)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.user = request.user
                new_post.slug = slugify(form.cleaned_data['body'][:30])
                new_post.save()
                messages.success(request, 'Your post edited successfully', 'success')
                return redirect('accounts:user_dashboard', user_id)
        else:
            form = EditPostForm(instance=post)
        return render(request, 'posts/edit_post.html', {'form': form})
    else:
        return redirect('posts:all_post')


@login_required
def add_reply(request, post_id, comment_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.reply = comment
            new_reply.is_reply = True
            new_reply.save()
            messages.success(request, 'Your reply added successfully', 'success')
            return redirect("posts:each_post", post.created.year, post.created.month, post.created.day, post.slug)


@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    like = Vote(post=post, user=request.user)
    like.save()
    return redirect("posts:each_post", post.created.year, post.created.month, post.created.day, post.slug)

sm/posts/templates/posts/add_post.html
{% extends 'base.html' %}
{% block title %} Add Post{% endblock %}
{% block content %}
<form action="" method="post">
    <div class="card-body text-center">
    {% csrf_token %}
    {{form.none_field_errors}}
    {{form.body.errors}}
    {{form.body}}
    </div><hr>
    <div class="text-center">
        <input class="btn" type="submit" value="Add Post" style="background-color:#85c27c;">
    </div>
</form>

{% endblock %}

sm/posts/templates/posts/all_posts.html
{% extends 'base.html'%}
{% block title %} Home {% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="card m-3">
            <p class="card-header"><a href="{% url 'accounts:user_dashboard' post.user.id %}" style="text-decoration: none; color: #466b4f;">{{post.user}}</a> | {{post.created}}</p>
            <a class="card-footer" href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black;"><p>{{post.body | truncatechars:500}}</p></a>
        </div>
    {% endfor %}
{% endblock %}

sm/posts/templates/posts/each_post.html
{% extends 'base.html' %}
{% block title %} {{post.user}} | Post {% endblock %}
{% block content %}
{% if request.user.is_authenticated and request.user.id == post.user.id %}
    <a style="text-decoration: none; color: #466b4f;" href="{% url 'posts:delete_post' request.user.id post.id %}">Delete Post &nbsp;</a>
    <a style="text-decoration: none; color: #466b4f;" href="{% url 'posts:edit_post' request.user.id post.id %}">Edit Post</a><hr>
{% endif %}
    <div class="card-header"><a href="#" style="text-decoration: none; color: #466b4f;">{{post.user}}</a> | {{post.created}} | {% if request.user.is_authenticated %}
        <a href="{% url 'posts:like_post' post.id %}" class="btn btn-outline-danger btn-sm {% if can_like %}disabled{% endif %} ">
            {% if can_like == False %}<3{% else %}{{ post.like_count }}{% endif %}</a>{% endif %}</div>
    <p class="card-footer">{{post.body}}</p>
{% if request.user.is_authenticated %}
        <form action="" method="post">
    <div class="card-body text-center">
        {% csrf_token %}
        {{form.none_field_errors}}
        {{form.body.errors}}
        {{form.body}}
    </div>
    <div class="text-center">
        <input class="btn" type="submit" value="Add Comment" style="background-color:#85c27c;">
    </div>
</form>
{% endif %}
    <div class="card-body">
        {% with total=comments.count%}
            <h4>this post has&nbsp;{{total}}&nbsp;comment{{total|pluralize}}</h4><hr>
        {% endwith %}
        {% for comment in comments %}
            <div class="card-body bg-dark text-white">
                <p class="card-header">{{comment.user}}</p>
                <p class="card-footer">{{comment.body}}</p>
                {% if request.user.is_authenticated %}
                 <form action="{% url 'posts:add_reply' post.id comment.id %}" method="post">
                            <div class="card-body text-center ">
                                {% csrf_token %}
                                {{reply_form.none_field_errors}}
                                {{reply_form.body.errors}}
                                {{reply_form.body}}
                            </div>
                            <div class="text-center">
                                <input class="btn mb-2" type="submit" value="Add Reply" style="background-color:#85c27c;">
                            </div>
                        </form>
                 {% endif %}
                {% for reply in comment.comment_reply.all %}
                <div class="card bg text-white" style="background-color: #466b4f;">
                    <p class="card-header">{{reply.user}}</p>
                    <p class="card-footer">{{reply.body}}</p>
                        <form action="{% url 'posts:add_reply' post.id comment.id %}" method="post">
                            <div class="card-body text-center ">
                                {% csrf_token %}
                                {{reply_form.none_field_errors}}
                                {{reply_form.body.errors}}
                                {{reply_form.body}}
                            </div>
                            <div class="text-center">
                                <input class="btn mb-2" type="submit" value="Add Reply" style="background-color:#85c27c;">
                            </div>
                        </form>

                </div><br>
                {% endfor %}
            </div><br>
        {% endfor %}
    </div>
{% endblock %}

sm/posts/templates/posts/edit_post.html
{% extends 'base.html' %}
{% block title %}Edit Post{% endblock %}
{% block content %}
    <form action="" method="post">
    <div class="card-body text-center">
    {% csrf_token %}
    {{form.none_field_errors}}
    {{form.body.errors}}
    {{form.body}}
    </div><hr>
    <div class="text-center">
        <input class="btn" type="submit" value="Edit Post" style="background-color:#85c27c;">
    </div>
</form>

{% endblock %}